### PR TITLE
attachElContent refactor + return this from remove

### PR DESCRIPTION
**Pull request by megawac**
- Use `$.trim` instead of `.trim` for some backwards compat
- Some code reuse between the two conditions in attachElContent
- Return this from `remove`

### CODE REVIEW

**Comment by tiagorg** [comment]
That is great, @megawac ! Thanks for your contribution.

One very slight thing that I've just noticed: I've seen @samccone doing ```Backbone.$``` instead of just ```$``` - specially for Browserify users - So it would be ```Backbone.$.trim(html)```

If you agree with that, please feel free to do it should you want it, I can also make this change here. Just let me know then :)

**Comment by megawac** [comment]
Good point done

**Comment by tiagorg** [comment]
Fantastic! Thanks a bunch! :)

**Comment by megawac** [comment]
Great, similar changes probably should be applied to mixin

**Comment by tiagorg** [comment]
That is correct. I have some local code with changes on the mixin to fix this scenario when the template is not composed of a single root element. I will surely apply your changes to it when I am pushing.

**Pull request merged**
